name: pytest_service.py
on:
  push:
    branches:
        - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9  # Replace 'x' with your desired Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install pytest-html
        pip install pytest requests
        pip install parse 
        pip install pytest_bdd
    - name: Run api on pytest
      run: pytest -v step_defs/test_service_steps.py --html=Report/test_demo_report.html
#
#    - name: Send Email Report
#      uses: actions/upload-artifact@v2
#      with:
#        name: Test Report
#        path: ./reports/loginpage.html
##
#    - name: Configure Gmail and Send Email
#      env:
#        GMAIL_USERNAME: ${{secrets.GMAIL_USERNAME}}
#        GMAIL_PASSWORD: ${{secrets.GMAIL_PASSWORD}}
#
#        RECIPIENT_EMAIL: nikil56789@gmail.com  # Replace with the recipient's email
#
#      run: |
#        python reports/send_email_script.py $GMAIL_USERNAME $GMAIL_PASSWORD $RECIPIENT_EMAIL
